version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userdb
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: SCHOOL_REGISTRATION
    ports:
      - '3306:3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      school_registration_network:
        aliases:
          - mysql_host
  api:
    image: school-registration:0.0.1-SNAPSHOT
    container_name: api
    ports:
      - '8082:8082'
    depends_on:
      - mysql
    networks:
      school_registration_network:
        aliases:
          - api_host
volumes:
  my-db: {}
networks:
  school_registration_network: